### ISSUE TITLE
invisible system tray icon

### ISSUE THREAD

**Issue by taprobane99** [nullobsi/clight-gui#10]
hi,

i am using kde plasma with dark theme. there is no tray icon just a blank space

this happens both with "light tray icon" ticked, and unticked.

**Comment by nullobsi** [comment]
hello, 

are you using arch/ the AUR package? the system tray icons are included in the binary but i believe this does not work on some configurations. you should be able to copy the icons in the repo under `src/resources/icons/` to `/usr/share/icons/hicolor/scalable/apps` and refresh the icon cache to get it to work

**Comment by famewolf** [comment]
I'm having the same issue and AM using the aur git package.  Black area where icon should be.
![Screenshot_20210502_023130](https://user-images.githubusercontent.com/4558832/116804761-6f87ab80-aaef-11eb-9b95-e96b552eb058.png)

**Comment by nullobsi** [comment]
have you already tried installing the icons to your system directory

**Comment by famewolf** [comment]
> have you already tried installing the icons to your system directory

Yes, and it worked as expected however the aur package should still be fixed to include the icons so it works under all conditions.

**Comment by nullobsi** [comment]
@yochananmarqos, could you update the PKGBUILD to include the icons? I think you should be able to just use `make install`, as the icons are installed with the cmakelists

**Comment by famewolf** [comment]
Not unless there's a tutorial that explains how to do it.

**Comment by nullobsi** [comment]
they are the current maintainer of the AUR package, so they have to update it.

you should be able to replace just the line
```
install -Dm755 "build/${pkgname%-git}" -t "$pkgdir/usr/bin"
```
with
```
make -C build install DESTDIR=$pkgdir
```
and it should also install the icons

**Comment by yochananmarqos** [comment]
@nullobsi 
> copy the icons in the repo under src/resources/icons/ to /usr/share/icons/hicolor/scalable/apps

It's `/usr/share/icons/hicolor/scalable/status`, [remember](https://github.com/nullobsi/clight-gui/issues/2#issuecomment-766285257)? 😉️ I see you [fixed the path](https://github.com/nullobsi/clight-gui/commit/48c95796eae05f97596e50056e64cb805cd6692f) now.

@famewolf I've updated the AUR package to install the icons.

**Comment by famewolf** [comment]
> @nullobsi
> 
> > copy the icons in the repo under src/resources/icons/ to /usr/share/icons/hicolor/scalable/apps
> 
> It's `/usr/share/icons/hicolor/scalable/status`, [remember](https://github.com/nullobsi/clight-gui/issues/2#issuecomment-766285257)?  I see you [fixed the path](https://github.com/nullobsi/clight-gui/commit/48c95796eae05f97596e50056e64cb805cd6692f) now.
> 
> @famewolf I've updated the AUR package to install the icons.

Thank you!   I would have helped if I coulld/knew how.   Gonna spend some time today searching/reading docs on modifying/building arch packages.  I remember I've used "makepkg -i" sometime in the past.  Clight has been very usable on my Lenova ideapad3 possibly because it gives an acpi backlight error on boot which requires adding "acpi_backlight=none" to the cmdline in /etc/default/grub.
