### ISSUE TITLE
Keyboard brightness setting pane is empty

### ISSUE THREAD

**Issue by jclsn** [nullobsi/clight-gui#17]
![grafik](https://user-images.githubusercontent.com/19779511/129488003-1634f637-ff98-422a-bec7-8fbc9d966c1e.png)

**Comment by nullobsi** [comment]
are you using the latest `clight-git`? it should say `Clight 4.7`

**Comment by jclsn** [comment]
Seems like the AUR script is not fetching the latest version. I deleted the cache and tried putting the latest commit hash. It always downloads 4.6.

**Comment by jclsn** [comment]
I compiled 4.7 manually. Works.
