### ISSUE TITLE
Check that various dbus APIs exposed by Clight exists before creating their tabs

### ISSUE THREAD

**Issue by FedeDP** [nullobsi/clight-gui#19]
Hi!

Following https://github.com/FedeDP/Clight/issues/221, Clight 4.7 will kill dbus API for unsupported modules.
This means that, eg: on my laptop keyboard module is unsupported thus its dbus API is not created.  
I think that clight-gui should avoid to show tabs for unsupported features (ie: those features whose API is not exposed on dbus).

**Comment by nullobsi** [comment]
done in latest commit :)
