### ISSUE TITLE
[Feature Request] Symbolic tray icon

### ISSUE THREAD

**Issue by yochananmarqos** [nullobsi/clight-gui#2]
The top bar on GNOME is dark no matter what theme is used and the new black tray icon is almost not visible.

**Comment by nullobsi** [comment]
i believe the icons can be changed using the icon name `high-brightness` and `low-brightness`, but that is a good idea

I'm not sure how to go about that though, an option should be fine?

**Comment by nullobsi** [comment]
my system has a clight icon in `/usr/local/icons/hicolor/scalable/apps/clight.svg` which is used for the main window icon, with a fallback included

i believe putting an icon in one of the XDG search paths under those names should work :P

**Comment by yochananmarqos** [comment]
No, I mean just since the last three commits since you switched to the Unicons. It was using what looked like `display-brightness` before.

![Screenshot from 2021-01-23 19-17-01](https://user-images.githubusercontent.com/5437803/105619430-f2da8800-5daf-11eb-956d-7b85e5956c98.png)

I have `/usr/share/icons/hicolor/scalable/apps/clight.svg`, but that doesn't help for the tray icon.

All that should be installed is the `clight-gui` binary, right?

**Comment by nullobsi** [comment]
yes, the clight-gui binary is all that is installed

the binary includes default resources, of which are included the icons for the tray icon. qt supports using themable icons, and so that is what i have done

putting alternative icons under `~/.local/share/icons/hicolor/status/` should change them; if you give me a moment I will upload white icons to the repo :)

**Comment by nullobsi** [comment]
Okay, I've pushed an update to the repo with dark and light icons included- the light icons can be copied to the local icons directory to override the included ones. But, I wonder if there's a way to change them automatically? I'll have to do more research :)

**Comment by yochananmarqos** [comment]
That makes no difference, unfortunately.

**Comment by nullobsi** [comment]
Seriously? Hmm, you can try installing them under the system directory (i think /usr/share/icons/hicolor/scalable/)

but that is very odd, let me check if I changed something

**Comment by yochananmarqos** [comment]
I tried both, actually. Sorry my first comment wasn't more specific.

**Comment by nullobsi** [comment]
everything seems to be working for me, copying the light icons to the directory... 
![image](https://user-images.githubusercontent.com/22283693/105620251-c161bc80-5daf-11eb-8e20-dde96ec4a2b7.png)
(now you can't see it on mine :P)
![image](https://user-images.githubusercontent.com/22283693/105620257-d0486f00-5daf-11eb-8cf2-5eb6d42681b2.png)

**Comment by nullobsi** [comment]
did you build the latest version? i changed some of the names to align with what the theme names were

**Comment by yochananmarqos** [comment]
Well, you initially mentioned the wrong directory and my brain is frazzled. 😉️

Yes, it's working installing them to `/usr/share/icons/hicolor/scalable/status/`.

**Comment by nullobsi** [comment]
Oops--sorry about that

Glad it's working fine now :) I'm hoping to find a way to make it change themes automatically

**Comment by yochananmarqos** [comment]
Maybe you could have an option like qBittorrent does? Normal / Mononchrome (dark) / Monochrome / (light)?

![Screenshot from 2021-01-23 20-43-06](https://user-images.githubusercontent.com/5437803/105620553-9c734680-5dbb-11eb-90f5-d11d1e268897.png)


![Screenshot from 2021-01-23 20-41-54](https://user-images.githubusercontent.com/5437803/105620547-8d8c9400-5dbb-11eb-8e93-5a8d903d4a29.png)

![Screenshot from 2021-01-23 20-43-24](https://user-images.githubusercontent.com/5437803/105620557-a85f0880-5dbb-11eb-9011-29bdeb8e540a.png)

**Comment by nullobsi** [comment]
i think that would be a good idea too. i'll be working on it soon :)

**Comment by nullobsi** [comment]
alright, i've added a checkbox option under Edit!

**Comment by nullobsi** [comment]
just so you know the icons installed by the pkgbuild override the built in ones, so the icon switching does not work...

**Comment by yochananmarqos** [comment]
> i've added a checkbox option under Edit!

That will work, thank you. 
> the icons installed by the pkgbuild override the built in ones

Yep, I've removed them.
