### ISSUE TITLE
lon and lat location are not being read in or written to the config file

### ISSUE THREAD

**Issue by elypter2** [nullobsi/clight-gui#21]
event_duration doesn't work either but sunset and sunrise and other settings do work.

**Comment by nullobsi** [comment]
Intresting, so when you press "store" the coordinates are not saved...?

i am not sure if thats an issue with clight or clight-GUI, so i will do some investigation later

**Comment by nullobsi** [comment]
I did some look and it turns out I never added the dbus call

But when I added it, it seems Clight ignores the new values. @FedeDP, is this something that is supported..? (I do not have Geoclue installed, and it defaults to 91,181)

**Comment by FedeDP** [comment]
Hi! @elypter2 on which Clight version is this happening?

@nullobsi as you can see here: https://github.com/FedeDP/Clight/blob/master/src/conf/config.c#L579, if it stores sunset and sunrise, it should be storing event_duration and latitude/longitude too! Very weird indeed!
When SetProperty is called on Conf.Daytime.Location, this gets called: https://github.com/FedeDP/Clight/blob/master/src/modules/interface.c#L642
It is a super simple method and should work, indeed. Can you enable verbose logging and see if 
`DEBUG("New location from BUS api: %.2lf %.2lf\n", loc_req.loc.new.lat, loc_req.loc.new.lat);`
line is properly logged?

EDIT: thank you anyway :)

**Comment by elypter2** [comment]
i am running version 4.7 on endeavouros

**Comment by FedeDP** [comment]
Uh, it seems like i forgot to actually store the newly set location in the conf structure, thus it was not being updated in the conf file and not saved :D 
It should now be fixed in Clight master: https://github.com/FedeDP/Clight/commit/51ba3206b945eb15293455cdc1c589dd97ea15a2. 

Weird thing is `event_duration` should work instead...
I will test and see what happens!

**Comment by FedeDP** [comment]
Ok i see: event_duration has no signal attached in clight-gui @nullobsi :
https://github.com/nullobsi/clight-gui/blob/main/src/gui/DaytimeTab.cpp#L19

With that fix, and clight-git, this should be fixed!

**Comment by nullobsi** [comment]
oops, i think those two were the things I may have forgot to connect

anyways, thanks for pointing this out, I have fixed both in 8652cdf :)
