### ISSUE TITLE
tray icon disappears when toggling the edit: light tray icon option

### ISSUE THREAD

**Issue by elypter2** [nullobsi/clight-gui#23]
it doesnt reappear regardless of the state of the toggle. the tray element is still functional but the icon is gone

**Comment by nullobsi** [comment]
what desktop environment are you using? if it's X11 based it may be using the application built-in icons, (Xembed) but if it's wayland or something like KDE/Gnome it is probably trying to use icons in the /usr/share/icons directory but failing

**Comment by elypter2** [comment]
Operating System: EndeavourOS
KDE Plasma Version: 5.23.2
KDE Frameworks Version: 5.87.0
Qt Version: 5.15.2
Kernel Version: 5.14.16-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5500U with Radeon Graphics
Memory: 7.1 GiB of RAM
Graphics Processor: AMD RENOIR

**Comment by yochananmarqos** [comment]
I can reproduce this on GNOME.

**Comment by nullobsi** [comment]
should be fixed in 539c149 :)
