### ISSUE TITLE
No Sensor Curve Backlight AC

### ISSUE THREAD

**Issue by fleamour** [nullobsi/clight-gui#24]
As above, I have set a custom profile for battery & would like to set the very same for AC also but there are no percentages shown to edit in AC sensor box?

In order to gain a editable sensor curve I need create new profile then the default profile has an AC sensor curve, however the newly created profile (Intel_Backlight) does not.

**Comment by nullobsi** [comment]
i don't have multiple monitors so i couldn't really test this feature properly,

but it works fine for me when I add a new profile. does it work if you create a new blank config file and restart clight?

**Comment by nullobsi** [comment]
i may make it so you can right click -> add a sensor point, or a button.

**Comment by fleamour** [comment]
It's not multiple monitors but running on battery or mains electricity (AC.)

**Comment by nullobsi** [comment]
that's interesting. I'm not sure what would cause that, but I will add options to delete and add sensor points

**Comment by nullobsi** [comment]
f601899 should add the ability to add regression points, let me know if that works for you :)
