### ISSUE TITLE
Brightness turns to 0 causing black screen

### ISSUE THREAD

**Issue by Zedai00** [nullobsi/clight-gui#28]
Im using arch linux and xmonad where if the brightness is 0 it completely turns the screen black and the clight-gui does that when in a dark place so can anything be done to fix that?

**Comment by FedeDP** [comment]
Hi! Thanks for reporting this!
Yes, you can update the first value of the backlight regression points in clight conf file (/etc/default/clight.conf).
I mean, by default ac and batt regression points start from 0.0; you just need to update that value to start from eg: 0.1.

**Comment by FedeDP** [comment]
I will make sure to add this info to the Clight FAQs!

**Comment by Zedai00** [comment]
Thanks Closing this

**Comment by FedeDP** [comment]
Here is the updated wiki: https://github.com/FedeDP/Clight/wiki/FAQ#clight-sets-0-backlight-level-but-my-screen-turns-black :)
