### ISSUE TITLE
Segfault on Arch build

### ISSUE THREAD

**Issue by dwlazlo** [nullobsi/clight-gui#3]
Hi, 
Not sure how much help I can be but clight-gui segfaulted on my machine.

I'm running a recent install of Arch with i3. Not much on the machine, so let me know which versions of other software I should check.

edited for more info.

**Comment by nullobsi** [comment]
i use arch myself and haven't had it segfault on me

to be honest, i'm not sure how to go about debugging this; you can try using gdb or another debugging tool to try and find out where the segfault happens. i know clight had some recently fixed issues involving the pause option, but i'm not sure.

**Comment by adriangoransson** [comment]
I'm also experiencing segfaults, on void linux. Happens immediately when trying to start the program.

I've never used cmake and there was no documentation on how to run it, so I just grabbed the args from the PKGBUILD file on aur. I did add PREFIX_PATH as there was complaints from cmake otherwise.

```
cmake -B build -S src -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_PREFIX=/usr -Wno-dev -DCMAKE_PREFIX_PATH=/usr/include/qt5/

make -C build
```

gdb output
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff2b76640 (LWP 26169)]
[New Thread 0x7ffff1f58640 (LWP 26170)]

Thread 1 "clight-gui" received signal SIGSEGV, Segmentation fault.
0x00007ffff71cde07 in QIcon::setIsMask(bool) () from /usr/lib/libQt5Gui.so.5
```

Tray icon issues perhaps? I don't have a system tray, I don't think. I'm using Bspwm and polybar.

**Comment by nullobsi** [comment]
okay, it segfaults on the QIcon::setIsMask call

that's supposed to help mitigate issues where the icon is dark on a dark background, or light on a light background, but I guess it doesn't like that. could you try removing it and see what happens? it's in `src/gui/MainWindow.cpp` on lines 13 and 14.

**Comment by adriangoransson** [comment]
That did indeed work. Thanks!

**Comment by nullobsi** [comment]
alright, i'll make a push to master removing those calls... though it's very odd it would cause that issue in the first place.

**Comment by dwlazlo** [comment]
Thanks, I might make a note that it's out of date on the AUR page.

Meanwhile I will figure out how to compile into a pkg ;)

**Comment by nullobsi** [comment]
the aur package should always build from latest master, even if it says something else on the page :)

**Comment by dwlazlo** [comment]
Yeah I was just trying to decipher that :)

Thanks I'll leave the maintainer out of this then lol.

**Comment by nullobsi** [comment]
if it fixes the issue for you, you can close the issue! thank you ;)

**Comment by dwlazlo** [comment]
Yep all good! Thank you for all your work and quick responses :)
