### ISSUE TITLE
no icon

### ISSUE THREAD

**Issue by promeneur** [nullobsi/clight-gui#4]
openSuse 15.2
kde apps 20.12.1
kde plasma 5.20.5
kde frameworks 5.78.0
qt 5.15.2

Hello

I build clight-gui.

There is no icon for the executable clight-gui just a default icon for an executable : a console with a "!".

If i launch clight-gui a space is displayed in systray but no icon.

Can you supply a script to be sure compilation is good because i don't know anything about C language  and compilation. I just know we must execute cmake, make statements.

Thanks

**Comment by yochananmarqos** [comment]
See my AUR [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/?h=clight-gui-git) for inspiration.

**Comment by promeneur** [comment]
ok thanks

but what about icon ?

**Comment by nullobsi** [comment]
I believe this is caused by the tray icon not accepting the provided icon by the application. Because the icon is not installed to a common directory, it tries to search for the icon and fails.

Later I will try to change some of the code to see if it mitigates the problem.

**Comment by nullobsi** [comment]
I've pushed a commit that adds icons for the tray into the system icon directory. Could you follow the build instructions in the readme to install the icons and see if that fixes the issue?

**Comment by promeneur** [comment]
no more problem with icons.

thanks
