### ISSUE TITLE
clight*gui does not get anything about clight conf or state

### ISSUE THREAD

**Issue by promeneur** [nullobsi/clight-gui#5]
openSuse 15.2
clight 4.0, clightd 4.0
 i build clight-gui.

If i launch clight-gui then

in "info" tab i get strange values

sunrise 1/1/1970 01 h 00
sunset 1/1/1970 01 h 00

location 91.000, 181.000 << completly false, must be 44.841, 0.580

in "day time" tab i get also strange value

location 0.000 lat, 0.000 lon
![info](https://user-images.githubusercontent.com/240424/106640244-1b1f6f00-6586-11eb-838e-be2181ba874a.png)

**Comment by nullobsi** [comment]
location 91,181 means that your location is not set. that's also why sunrise and sunset are strange values, it doesn't know where you are. these locations can be overridden in the Daytime tab.

**Comment by promeneur** [comment]
The command clight acquires good coordinates dynamically with geoclue. I checked this by launching manually the command clight.
How clight-gui get these coordinates ?

**Comment by FedeDP** [comment]
Hi! @promeneur you should update Clight and Clightd to latest versions!
@nullobsi i'ts better to explicitly require Clight >= 4.2 eg: in repository's readme, i guess!

**Comment by nullobsi** [comment]
i assumed it was a versioning issue... i'll add that to the readme. Thank you!

**Comment by FedeDP** [comment]
Well indeed I did not break API since clight 4.0...but in any case I guess it is just a versioning issue. Let's see if it fixes the issue!

**Comment by promeneur** [comment]
i can't compile clight > 4.0 and clightd > 4.2 !

i wait for answer for these problem.

thanks

**Comment by promeneur** [comment]
Now clight and clightd latest version are compliant with openSuse 15.2. FedeDP kindly did that.
Now no more problem with clight-gui.

**Comment by nullobsi** [comment]
Great! Glad everything is working :)
