### ISSUE TITLE
[Wayland] running clight-gui resets gamma

### ISSUE THREAD

**Issue by nullobsi** [nullobsi/clight-gui#6]
running clight-gui while on Wayland resets gamma

dbus call to Clightd causes connection to reset (?)

**Comment by nullobsi** [comment]
this may not just be a clight gui issue, it seems to be random and sporadic...

**Comment by FedeDP** [comment]
> dbus call to Clightd causes connection to reset (?)

Hi! Can you tell me which call is causing the connection reset?

> this may not just be a clight gui issue, it seems to be random and sporadic...

Unfortunately sway gamma management requires the connection to be kept alive, see https://github.com/swaywm/wlroots/issues/2455 for more details. 
Thus, if clightd is crashing for some reason, screen temp is resetted.
We need to understand why clightd is crashing, feel free to open a bug report on clightd repo!
Thanks!
