### ISSUE TITLE
clight-gui, does not start minimized when launching by opening a kde session

### ISSUE THREAD

**Issue by promeneur** [nullobsi/clight-gui#7]
When opening a kde session clight-gui is automatically launched but not minimized. It's not handy.
I did not find this feature in settings.

It would be a good thing.

Thanks

**Comment by yochananmarqos** [comment]
Use `clight-gui --tray` for the startup command to accomplish that.

**Comment by promeneur** [comment]
I can't do this. He is not me which starts clight-gui but kde.

When you launch an app which docks in systray, and you don't quit it when you close the kde session then kde systray records the app in systray settings. When you open a kde session then kde launches the app.

**Comment by nullobsi** [comment]
I feel like this isn't an issue with clight-gui. I don't use KDE, but there must be a way to prevent this behavior.

**Comment by promeneur** [comment]
Is there a way to put some statement as "systray=1" in a conf file for clight-gui ?

**Comment by nullobsi** [comment]
no; you are expected to use the `--tray` command option...

but maybe a config would be nice. I'll add it probably tomorrow.

**Comment by promeneur** [comment]
Thanks

**Comment by nullobsi** [comment]
Hello,

I've added this to the config. If you build from the master branch, you should be able to add `start-in-tray=true` to make it launch straight to the tray. You can close the issue if this works for you :)

**Comment by promeneur** [comment]
Problem solved.

Thanks for all.
