### ISSUE TITLE
brightness indicator laways at 0%

### ISSUE THREAD

**Issue by promeneur** [nullobsi/clight-gui#8]
Hello

in contextual menu we get always an item "brightness 0 %"

see capture
![brightness](https://user-images.githubusercontent.com/240424/107112876-2e1e9180-685b-11eb-872a-fc3116f1542c.png)

**Comment by nullobsi** [comment]
i don't know where to start with this--does it show under the backlight tab? how many monitors?

**Comment by promeneur** [comment]
With clight 4.0 and clightd 4.0 this show a value different from 0.

I get one monitor.

See

 the backlight tab
![backlight_tab](https://user-images.githubusercontent.com/240424/107113041-7f7b5080-685c-11eb-8a5e-22a57f6d16cf.png)

**Comment by nullobsi** [comment]
what's the output of `busctl --user get-property org.clight.clight /org/clight/clight org.clight.clight BlPct`?

**Comment by promeneur** [comment]
x@grognon:~> busctl --user get-property org.clight.clight /org/clight/clight org.clight.clight BlPct
d 0
x@grognon:~>

**Comment by nullobsi** [comment]
hmm, it seems clight is not properly reporting the brightness value then. i'm not sure why- i think it's supposed to take the brightness of the first monitor.

this isn't really a clight-gui bug then, but since it doesn't happen to me it's a bit strange.

**Comment by promeneur** [comment]
As you can see i use clight 4.3 and clightd 5.2, the master branch. Because master branch is compliant to openSuse 15.2.

**Comment by nullobsi** [comment]
perhaps it's something odd with your setup, i don't use opensuse so I can't exactly test this.

**Comment by promeneur** [comment]
i opened a bug report at clight.

https://github.com/FedeDP/Clight/issues/183

**Comment by promeneur** [comment]
Problem solved. It was a clightd problem.
