### ISSUE TITLE
Settings not applied

### ISSUE THREAD

**Issue by ralphee** [nullobsi/clight-gui#9]
arch linux 
clight v 4.3
clightd v 5.2

none of settings (time/location/backlight etc)are being applied. When re-opening clight-gui has reverted to default settings

**Comment by yochananmarqos** [comment]
If `~/.config/clight.conf` does not exist, Clight will use `/etc/default/clight.conf`. Copy the system config file to your user config directory and restart the Clightd service.

@nullobsi Could you add detection for the user config file and warn the user if it's not found?

**Comment by ralphee** [comment]
> If `~/.config/clight.conf` does not exist, Clight will use `/etc/default/clight.conf`. Copy the system config file to your user config directory and restart the Clightd service.
> 
> @nullobsi Could you add detection for the user config file and warn the user if it's not found?

i had already copied the config file; btw forgot to mention I am using wayland [hikari](https://aur.archlinux.org/packages/hikari/)

**Comment by nullobsi** [comment]
are you clicking the "store" button in the bottom write? that commits your changes to the config file

**Comment by ralphee** [comment]
started from scratch and settings are being saved now (The only diff in methodology was to kill clightd process directly from atop). Thxs all for your kind patience!
